---

- name: Include OS-specific variables
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - main.yml

- name: Define keepalived_daemon_options variable
  set_fact:
    keepalived_daemon_options: "{{ __keepalived_daemon_options }}"
  when: (keepalived_daemon_options is not defined) or
        (keepalived_daemon_options == "")
